### Import Libraries 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as ply
%matplotlib inline

import seaborn as sns
sns.set_style('whitegrid')
sns.set_context('poster')

import sklearn 
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

### Data

In [2]:
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()

dir(cancer)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

### Labels and Features

In [3]:
labels = cancer['target']
print(labels)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [4]:
features = cancer['data']
print(features)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [5]:
print(cancer['feature_names'])

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


### Train and Test Data

In [15]:
train, test, train_labels, test_labels = train_test_split(features,
                                                          labels,
                                                          test_size=0.33,
                                                          random_state=42)
print('train',train.shape)
print('train_labels',train_labels.shape)
print('test',test.shape)
print('test_labels',test_labels.shape)

train (381, 30)
train_labels (381,)
test (188, 30)
test_labels (188,)


In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(features, labels, test_size = .33, random_state = 5)
print('X_train',X_train.shape)
print('X_test',X_test.shape)
print('Y_train',Y_train.shape)
print('Y_test',Y_test.shape)

X_train (381, 30)
X_test (188, 30)
Y_train (381,)
Y_test (188,)


### Model

In [8]:
gnb = GaussianNB()
model = gnb.fit(train, train_labels)
preds = gnb.predict(test)
print(accuracy_score(test_labels, preds))

0.9414893617021277


In [17]:
gnb = GaussianNB()
model = gnb.fit(X_train, Y_train)
preds2 = gnb.predict(X_test)
print(accuracy_score(Y_test, preds2))

0.9468085106382979


### Confusion Matrix

In [10]:
sklearn.metrics.confusion_matrix(test_labels, preds, labels=None, sample_weight=None)

array([[ 61,   6],
       [  5, 116]], dtype=int64)

In [18]:
sklearn.metrics.confusion_matrix(Y_test, preds2, labels=None, sample_weight=None)

array([[ 62,   4],
       [  6, 116]], dtype=int64)

### AVerage Percision

In [12]:
from sklearn.metrics import average_precision_score
average_precision = average_precision_score(test_labels, preds)
print(average_precision)

0.9381253477156701


In [19]:
from sklearn.metrics import average_precision_score
average_precision2 = average_precision_score(Y_test, preds2)
print(average_precision2)

0.9510405766771305
